<?php
return [
    'github' => 'github',
    'xing' => 'xing',
    'bluesky' => 'cloud',
    'twitter' => 'twitter',
    'facebook' => 'facebook',
    'linkedin' => 'linkedin',
    'instagram' => 'instagram',
    'youtube' => 'youtube',
    'tiktok' => 'tiktok',
    'whatsapp' => 'whatsapp',
    'snapchat' => 'snapchat-ghost',
    'reddit' => 'reddit',
    'pinterest' => 'pinterest',
    'telegram' => 'telegram',
    'discord' => 'discord',
    'medium' => 'medium',
    'vimeo' => 'vimeo',
    'twitch' => 'twitch',
    'spotify' => 'spotify',
    'slack' => 'slack',
    'dribbble' => 'dribbble',
    'behance' => 'behance',
    'flickr' => 'flickr',
    'mastodon' => 'mastodon',
    'goodreads' => 'book',
    'strava' => 'strava',
    'rss' => 'rss',
    'zoom' => 'video',
    'bsky' => 'cloud'
]; 